mart1ver/oressource

INSTALL.md, moteur/dbconfig.php
..... et suppression du mot de passe dans le fichier de config :)
=> Procédure d'install 

ifaces/bilanv.php
Ne pas afficher les Points de Vente invisibles dans les onglets de la page du bilan des ventes
=> Cacher les Points de Vente invisibles

images/index.php
voir https://github.com/mart1ver/oressource/pull/33
=> Suppression des short_open_tags 2 (Suite PR #33)

ifaces/bilanc.php, ifaces/bilanhb.php, ifaces/bilanv.php, ifaces/collecte.php, ifaces/index.php, ifaces/remboursement.php, ifaces/sorties.php, ifaces/sortiesc.php, ifaces/sortiesd.php, ifaces/sortiesp.php, ifaces/sortiesr.php, ifaces/ventes.php, ifaces/verif_collecte.php, ifaces/verif_sorties.php, ifaces/verif_vente.php, js/utilitaire.js, js/ventes.js
Normalement aucun problème n'est ajouté par cette pull request.
Vérifier les erreurs PHP en changeant la configuration: `display_errors = on` et `log_errors = on` dans le fichier `/etc/php5/apache2/php.in`.
=> Regroupement de fonctions redondantes JS et réecritures.

js/utilitaire.js
Fixe un bug introduit dans le commit e0ba4c371f476b96febc356bbd44f4a6278f2b59.
Sur la page de sorties recyclages le choix de distributeur ne se grisais plus.
=> Fix bug sur sortier.

ifaces/bilanc.php, ifaces/bilanhb.php, ifaces/bilanv.php, ifaces/collecte.php, ifaces/sorties.php, ifaces/sortiesc.php, ifaces/sortiesd.php, ifaces/sortiesr.php, ifaces/verif_collecte.php, ifaces/viz_vente.php
Fermetures de balises ajoutées, d'attributs mal déclarer.
=> Erreurs HTML

css/oressource.css, ifaces/bilanc.php, ifaces/bilanhb.php, ifaces/bilanv.php, ifaces/collecte.php, ifaces/sorties.php, ifaces/sortiesc.php, ifaces/sortiesd.php, ifaces/sortiesp.php, ifaces/sortiesr.php, ifaces/verif_collecte.php, ifaces/viz_vente.php, js/utilitaire.js
Intégrer après https://github.com/mart1ver/oressource/pull/75.
Interfaces impactées:
=> Ajout d'indicateurs d'erreurs lors de saisies invalides.

ifaces/index.php
@mart1ver, J'ai réécrit l'index pour la V1 et je me suis dit que retro-porter les changements dans la version actuelle serait pas totalement idiot.
@daamien Si tu veux faire une relecture avant qu'on fusionne cette branche. :)
=> Reecriture de la page d'acceuil.

ifaces/bilanv.php, ifaces/sorties.php, ifaces/sortiesc.php, ifaces/sortiesd.php, ifaces/sortiesp.php, ifaces/sortiesr.php, mysql/recap_CA_par_mode_paiement_tout_les points.sql
Dans les formulaires de sortie hors boutique, on requête sur les point de collecte au lieu des points de sortie hors boutique
=> Correction pesée max dans sortie hors boutique

README.md, SAUVEGARDE.md
J'ai repris les explications que j'avais rédigé pour recyclodrome et j'en ai fait un fichier à part entière pour que ce soit plus facile d'accès. J'ai l'impression que dans la plupart des cas les sauvegardes ne sont pas faites alors qu'on parle quand même de données comptables...
=> FIX #87 : Procédure de sauvegarde

core/session.php, ifaces/collecte.php, ifaces/index.php, ifaces/sortiesc.php, ifaces/tete.php
Réécriture du JS, PHP et de certains bouts de requêtes sql.
J'ai commencé à faire des fonctions pour factoriser un peu le code aussi.
Si tu as des questions hésite pas.
=> Réécriture de ifaces/index.php pour plus de simplicite

core/session.php, ifaces/collecte.php, ifaces/index.php
Réécriture et modification profonde de la page.
Ajoute la notion de transaction au sens ou on peux à présent ajouter pesée par
pesée au lieu d'avoir un décompte global d'un type de pesée.
Côté serveur on gardera la séparation par item par soucis de traçabilité.
Affichage plus léger dans l'interface de pesée.
=> (Ne pas merger) Réecriture de collecte.php

css/oressource.css, ifaces/collecte.php, ifaces/pied.php, js/numpad.js, js/ticket.js, moteur/collecte_post.php
Gestion des entrées avec filtrage et lancement d'erreurs en cas de saisie incorrecte.
Amélioration de la page de collecte.
~Pour l'instant cela casse la saisie cote post. Je fini ça demain soir.~
Ça casse encore deux trois trucs mais c'est sur les rails.
=> [A tester]Reecriture de moteur/collecte_post.php

INSTALL.md
Rajout de la possibilité d'utiliser php7, php-fpm, nginx ou mariadb.
=> Mise à jour de INSTALL.md

core/requetes.php, core/session.php, core/validation.php, css/oressource.css, ifaces/collecte.php, ifaces/login.php, ifaces/sorties.php, ifaces/tete.php, js/ticket.js, moteur/collecte_post.php, moteur/login_post.php, moteur/sorties_post.php
Cote client:
- Changements dans la gestion des tickets cote client
- Et de l'encaissement histoire de pas faire doublon
- Rajout d'un toast/overlay de login en cas de session timeout sur les collectes et `sorties.php`
Cote Serveur:
- Rajout de fonctions de validation et de vérification de la session.
- Modification de la page de `sorties.php`
- Passage au JSON pour les dialogues sur `sorties.php`
- Utilisation de JSON pour le log-in.
Échange client serveur retrait des droits dans l’échange on les a déjà
cote serveur en vérifiant l'ID.
=> [A tester]Reecriture des sorties/Log-in

ifaces/login.php, js/ticket.js, moteur/login_post.php
Bon rien de grave c’était juste un `var_dump` qui traînait cote serveur.
J'en ai profiter pour ajouter une ébauche de documentation du mécanisme de login actuel par json.
Corrige: https://github.com/mart1ver/oressource/issues/112.
=> Fix du login ajout de documentation.

ifaces/edition_points_vente.php, ifaces/modification_points_vente.php, moteur/edition_points_vente_post.php, moteur/modification_points_vente_post.php
J'ai pris le temps de nettoyer car j'avais une exception dans une des pages.
Faut vérifier que ça casse rien. A terme faudra reprendre plus proprement.
C'est provisoire comme modification.
Attention j'ai changer le comportement des pages pour demander les valeurs de la
base et ne pas faire confiance aux données POST/GET. Vérifie si ça te va. :)
=> [Gelée] Nettoyage des editions/creations de points de ventes.

core/requetes.php, ifaces/bilanv.php, ifaces/index.php
Hello c'est pour tester ne la merge pas tant que https://github.com/mart1ver/oressource/pull/110
n'est pas passé.
Ou alors pour la tester en local fait un
```shell
git remote add axel https://github.com/darnuria/oressource
git fetch axel # Récupéré mes branches publiées.
git checkout -b axel/nettoyage/bilanv nettoyage/bilanv # Sauter dans ma branche distante
git checkout dev # Pour retourner à ton dev.
```
=> [Gelée] Nettoyage des bilans des ventes.

api/collectes.php, core/requetes.php
Fix du bug on essayait de récupérer d'indexer sur un entier...
```
-  $reponse = nb_categories_dechets_item($bdd);
-  $nombreCategories = (int) $reponse->fetch()['nombrecat'];
+  $nombreCategories = nb_categories_dechets_item($bdd);
```
Rapport de bug: #123 
OCollecte cassée pas d'encaissement pas de bad request lève une exception
PHP dans `requête.php` ligne 166.
Régression introduite par abb5ef5
stacktrace:
```html
[Tue Mar 07 19:54:48.099154 2017] [:error] [pid 1521] [client
127.0.0.1:47902] PHP Warning:  Invalid argument supplied for foreach() in
/var/www/oressource/ifaces/collecte.php on line 117, referer:
http://localhost/ifaces/
[Tue Mar 07 19:54:48.123646 2017] [:error] [pid 1521] [client
127.0.0.1:47902] PHP Stack trace:, referer: http://localhost/ifaces/
[Tue Mar 07 …
```
=> Fix:#123 Collecte impossible à saisir

api/sorties.php, ifaces/sortiesc.php, ifaces/sortiesr.php
=> Fix: #125 Sorties poubelles et Recyclages cassees.

ifaces/tete.php
Affecte les liens vers les sorties collectes et ventes.
=> Corrige les multiples espaces dans des URL de tete.php

INSTALL.md, README.md
Amelioration de la section devellopement deplacee dans README.md
=> Update du readme mise a jour versions php

core/requetes.php, ifaces/bilanv.php
- Gain en performances sensibles 3415ms pour afficher l'historique complet de la petite rck sur ma machine!
- Gain en lisibilité le code est similaire pour tout les points de ventes ou un seul.
Des petits bugs d'affichage sont sûrement présents.
=> Recriture des bilans ventes.

core/requetes.php, ifaces/grilles_prix.php
Vérifier que les fonctionnalités sont toujours la.
=> Fix: la page etait cassee.

ifaces/ventes.php
Identation et echo tags. Peu de changements importants.
=> Premiere passe de nettoyage.

ifaces/edition_mdp_admin.php, ifaces/edition_mdp_utilisateur.php, moteur/convention_sortie_post.php, moteur/edition_description_post.php, moteur/edition_localites_post.php, moteur/edition_mdp_admin_post.php
Quelques verifications sont peut-etre neccessaire.
=> Petit menage des sources.

ifaces/bilanv.php
Le diff est énorme car j'ai ré-indenté le ficher...
=> Fix tete.php + fix indentation

ifaces/sortiesd.php
La variable `$date` n'était pas déclaré.
=> Réinsertion de la variable $date dans le fichier sortiesd.php

ifaces/bilanc.php, ifaces/bilanv.php
Et fix d'une erreur de typographie dans les bilans
de collecte.
Aussi à présent si il n'y à pas de données à afficher alors on n'affiche
pas le bilan des pesées à la ventes.
=> Correction du bug du timepicker au bilans ventes

core/validation.php, ifaces/collecte.php, js/ticket.js
Ce commit résout le soucis du à la vérification de la localité et du type de
collecte ou de sortie en cours.
En effet tout les « tickets » n'ont pas d'id d'action et toutes les sorties
n'ont pas de localité.
=> Résout le bug due à la réintroduction des placesholders.

api/collectes.php, api/sorties.php
Gestion d'exceptions oubliées précédemment et de divers petits bugs.
=> Refactoring du code pour les sorties et les collectes

api/sorties.php, ifaces/sorties.php, ifaces/sortiesc.php, js/ticket.js
Fix aussi un bug réintroduit dans `api/sorties.php` et deux bugs dans `js/ticket.js`.
=> Fixplaceholder

core/requetes.php, core/session.php, core/validation.php
C'est un peu une horreur à relire c'est beaucoup de changements automatisées. 
J'ai pas encore fini.
Si vous avez le courage de relire dans les grandes lignes ça serais déjà bien.
Ne l'intégrez pas tout de suite.
=> Refactoring axel

api/sorties.php, ifaces/sorties.php, ifaces/sortiesc.php, ifaces/sortiesd.php, ifaces/sortiesp.php, ifaces/sortiesr.php, js/ticket.js
Et correction de quelques bugs.
=> Fix de la logique pour le choix du recycleur.

core/requetes.php, core/session.php, core/validation.php
Reverts mart1ver/oressource#203
=> Revert "Refactoring axel"

.editorconfig
=> Création d'un fichier de configuration d'Editeur

moteur/vente_post.php
=> Resolution d'un bug qui empechait d'enregistrer les ventes.

js/ticket.js
On renvoyais l'id suivant et pas courant...
=> Fix bug dans l'ajout d'objets dans un Ticket.

ifaces/bilanc.php, ifaces/bilanhb.php, ifaces/bilanv.php, ifaces/jours.php, ifaces/tete.php, ifaces/verif_collecte.php, ifaces/verif_sorties.php, ifaces/verif_vente.php, ifaces/viz_caisse.php, js/utils.js
Enlève pas mal de code en doublon j'ai porter le code pour le sélectionneur de date dans `utils.js`.
=> Factorisation du code pour le datepicker.

core/composants.php, ifaces/edition_utilisateurs.php, ifaces/utilisateurs.php
=> Fix utilisateurs

core/requetes.php
Etait du a une erreur de typage dans la signature de la fonction `insert_sortie`
=> Fix #246 crash soumission de sorties.

core/validation.php
Finalement on ne lancera pas d'exception les valeurs autres que oui seront false.
=> Correctif sur les oui/non.

.gitignore, UPGRADE.md, mysql/upgrade_20161011.sql, mysql/upgrade_20170627.sql
Commence à résoudre #243.
Ces commits se contentent de pouvoir amener sa vieille version au niveau actuel de la branche master.
2 fichiers .sql de plus à exécuter pour mettre à jour sa bd.
=> Scripts de maj de la bd

.gitignore, core/requetes.php, ifaces/viz_caisse.php
bug non signalé encore, sur la visualisation des dernières ventes.
(+vim dans .gitignore)
=> bug sur la visualisation des dernières ventes

core/composants.php, core/session.php, ifaces/collecte.php, ifaces/sorties.php, ifaces/sortiesc.php, ifaces/sortiesd.php, ifaces/sortiesp.php, ifaces/ventes.php
On pouvait saisir une date alors que la configuration l'interdit si un
utilisateur avait le droit 'e' édition date.
Et factorise aussi à l'aide d'un composant la GUI du ticket.
=> Correctif d'un bug de GUI avec les dates.

core/composants.php, ifaces/bilanc.php, ifaces/bilanhb.php
J'ai principalement tenter d’éliminer la part de code duplique dans le bilan hors-boutique.
=> Debut de refactoring dans les bilans de collectes et sorties.

ifaces/sortiesd.php, ifaces/sortiesp.php, ifaces/sortiesr.php
Introduit par: b97ee7f35e340e934804d8174d0c3e1e3422c708
@mart1ver corrige ce qu'on avait vu hier.
=> Fix de plusieurs bugs introduit recements dans les sorties.

core/requetes.php, ifaces/bilanc.php, ifaces/bilanhb.php
Continuité du re-factoring des collectes hors-boutique et de collecte.
=> Refactoring des bilans collectes et hors-boutique.

core/requetes.php, ifaces/edition_conventions_sortie.php
Correction du bug liée à l'utilisation de `$_GET` même si non assigné.
Utilisation de composants, nettoyage.
=> Nettoyage de la page edition_conventions_sorties.php

api/ventes.php, core/requetes.php, ifaces/bilanv.php
On associait l'id de vente et non l'id de vendus dans
pesee_vendus.id_vendus...
A quand des foreign keys?
=> Fix: Bug dans l'insertion d'une vente pesee.

ifaces/tete.php
On ne verifiais pas les droits d'un utilisateur sur un point donné.
=> Corrige un bug rendais visibles dans la navbar tout les points.

ifaces/edition_filieres_sortie.php, ifaces/edition_localites.php, ifaces/edition_points_collecte.php, ifaces/edition_types_contenants.php, ifaces/edition_types_poubelles.php, ifaces/modification_convention_sortie.php, ifaces/modification_filiere_sortie.php, ifaces/modification_moyens_paiement.php, ifaces/modification_points_collecte.php, ifaces/modification_points_sortie.php, ifaces/modification_points_vente.php, ifaces/modification_type_contenants.php, ifaces/modification_types_collecte.php, ifaces/modification_types_dechets.php, ifaces/modification_types_dechets_evac.php, ifaces/modification_types_sortie.php
Juste du nettoyage normalement pas de changement profonds.
=> Nettoyage des sources.

core/composants.php, ifaces/conventions_sortie.php, ifaces/moyens_paiment.php, ifaces/types_collecte.php, ifaces/types_dechets.php, ifaces/types_dechets_evac.php, ifaces/types_sortie.php
=> Refactoring des pages de configuration a 3 input.

ifaces/verif_collecte.php, ifaces/verif_sorties.php
J'étais parti pour juste corriger un bug puis en fait j'ai fait un petit nettoyage.
=> Fix/date unset + nettoyage des sources

core/validation.php, moteur/remboursement_post.php, mysql/2017-12-18_drop_adherents.sql
Attention il faut charger le script `mysql/2017-12-22_drop_adherents.sql` sql dans la database pour que ce commit ne casse pas tout.
=> Les adhérents ne sont plus utilisé nul part on peux donc les virer.

api/ventes.php
Il n'y avait pas coté SQL de valeur par defaut sur les remboursements.
=> 💊 Fix sur ventes.php.

api/collectes.php, api/sorties.php, core/composants.php, core/requetes.php, core/session.php, core/validation.php, ifaces/edition_types_poubelles.php, ifaces/modification_type_poubelles.php, ifaces/remboursement.php, ifaces/viz_caisse.php, ifaces/viz_vente.php, moteur/convention_sortie_post.php, moteur/edition_localites_post.php, moteur/export_bilans.php, moteur/filiere_sortie_post.php, moteur/grilles_prix_post.php, moteur/modification_type_poubelles_post.php, moteur/moyens_paiement_post.php, moteur/remboursement_post.php, moteur/type_contenants_post.php, moteur/type_poubelles_post.php, moteur/types_collecte_post.php, moteur/types_dechets_evac_post.php, moteur/types_dechets_post.php, moteur/types_sortie_post.php, moteur/visible.php, mysql/2017-12-29_remove_oui_non.sql
Remplacé par un `tiny int`/`bool` coté base. Par défaut il est à `1`/`true` ça simplifie le code des insertions.
=> Fin des 'oui'/'non' coté base.

core/composants.php, ifaces/bilanc.php, ifaces/bilanhb.php, ifaces/bilanv.php, ifaces/jours.php, ifaces/verif_sorties.php, ifaces/verif_vente.php, js/utils.js
A présent tout est encapsuler dans l'appel de la fonction `datePicker`
PHP et le `<script>` qui va avec.
=> Refactoring autour du datepicker pour en faire un composant.

core/composants.php, ifaces/bilanc.php, ifaces/index.php, ifaces/jours.php, ifaces/verif_collecte.php, js/utils.js
@mart1ver: Je te l'avais dit qu'on pouvait faire plus court. :)
=> Refactoring de jours.php.

core/configs.php
Le bug empêchait d'inséré des points j'avais oublier de changer le format d'insertion.
=> Fix d'un bug liée aux changements dans la base.

ifaces/index.php, js/utils.js
On avait pas besoin des requêtes vu que l'on va chercher les données
pour les graphs Morris autant utiliser celles la.
Et fix d'un bug liée à un oubli de fonction dans utils.js lors qu'un
réfactoring...
=> Supression de rêquêtes redondantes.

moteur/edition_localites_post.php
J'avais oublier le champ visible sans lui donner de valeur.
=> Correction d'un bug dans la creation d'une localité.

core/requetes.php, ifaces/edition_filieres_sortie.php, ifaces/modification_filiere_sortie.php, ifaces/modification_verif_collecte.php, ifaces/modification_verif_sorties.php, ifaces/modification_verification_remboursement.php, ifaces/modification_verification_vente.php, ifaces/verif_collecte.php, ifaces/verif_sorties.php, ifaces/verif_vente.php, ifaces/viz_vente.php
J'ai fini par faire une fonction auxillière pour reordonner une liste
d'array par une clé donnée. C'est la fonction map_by.
=> Création d'une fonction auxillière et refactoring.

moteur/dbconfig.php.example
Les options permettent de mieux diagnostiquer des erreurs avec la DB et de gérer les erreurs/clefs etrangères avec des exceptions.
=> Ajouts d'options pour la connection à la base de donnée.

ifaces/exportbase.php, ifaces/structures.php
ajout du bouton "sauvegarder la base  dans le panneau de config"
=> sauvegarde de la base

core/requetes.php, ifaces/bilanhb.php, ifaces/jours.php, js/ventes.js
Cas on souhaite vendre 5 cables electriques à l'unité a 1€.
- 5 * 1€ = 5€
Puis on souhaite vendre 5 cables electriques en lot à 3€ (aujourd'hui c'est
soldes).
- 1 (lot de 5 cables) * 3 = 5€
Si c'est ce que l'ont souhaitais faire notre ancien code n'y parvenais pas.
On avait des soucis sur la somme ainsi que pour afficher le bon "prix total".
=> Fix: Prix au lot et à l'unité

ifaces/collecte.php, ifaces/sorties.php, ifaces/sortiesc.php, ifaces/sortiesd.php, ifaces/sortiesp.php, ifaces/sortiesr.php, ifaces/ventes.php, js/ticket.js, js/utils.js, js/ventes.js
Bon ça commence a fonctionner encore 2 ou 3h dessus et c'est bon.
reste à faire:
=> Retour des fonctionnalité d'impressions pour les ventes.

core/requetes.php
https://github.com/mart1ver/oressource/issues/359
=> FIX #359 on «ajoutais le php» au lieu de «l'executer»

api/collectes.php, api/sorties.php, api/ventes.php, core/requetes.php
Corrections d'avertissement émis par [psalm](https://psalm.dev) un analyseur statique de php.
=> Analyse statique psalm

changelog.md, js/utils.js, js/ventes.js
Les sous-totaux étaient pas très fonctionnels.
- #391 Reprise du calcul de la TVA c'était pas trop ça.
Merci à deux bénévoles de la ressourcerie Le Cercle pour avoir remonter
les bugs.
=> Reprise du formatage dechets/objets, retrait des sous totaux.

js/utils.js
Co-authored-by: Axel Viala <axel.viala@darnuria.eu>
=> Change lineBreakSize + change showTicket.
