mart1ver/oressource

moteur/login_post.php

Le tag <? n'est pas accepté sur certains environements.
Je suggère d'utiliser le tag <?php partout pour éviter des problèmes.

Utilisation systématique du tag <?php

---

ifaces/bilanv.php
mysql/recap_CA_par_mode_paiement.sql

Tableau de recap du Chiffre d'Affaire par mode de paiement
Utile pour vérifier le fond de caisse en fin de vente
Equivalent de la touche 'Z' sur une caisse enregistreuse

recap des ventes par moyen de paiement

---

moteur/dbconfig.php.exemple

Meilleur gestion du try/catch au lieu de la faire sur chaque page, on le fait une fois pour toute dans le fichier de conf

déplacement du try/catch dans le fichier dbconfig

---

.gitignore
mysql/recap_CA_par_mode_paiement.sql

en ajoutant ce fichier .gitignore est sur que le fichier moteur/dbconfig.php ne sera jamais envoyé sur le dépot github et donc on évite de publier les codes d'accès à la base par erreur.
Pour les utilisateurs qui installe oressource, il faudrait fournir un fichier `dbconfig.php.exemple` qu'ils pourront copier et modifier

Ne pas envoyer les mots de passe sur le dépot Git :)

---

ifaces/ventes.php

Dans le panneau "Type d'objet" :  
S'il n'y pas de tarif prédéfini pour un type de déchets 
Alors on affiche un bouton tout simple  sans menu déroulant (ce qui fait  click de moins pour l'utilisateur)
Sinon s'il y a une grille de tarif  pour ce type de déchets
Alors on affiche un menu déroulant comme avant

Ecran de vente : simplification des boutons

---

ifaces/sortiesr.php

Fonctionne sans recharger la page.
Pour plus tard utiliser un 'placeholder' plutôt que d'avoir une première
option impossible à sélectionner.

Ajout d'une fonction pour reset l'ui des recycleur

---

core/validation.php

La validation échouais car on utilisait une option de filtre et non
un filtre dans la configuration du filtrage
Corrige également pour le champ localité.
Explication:
`FILTER_REQUIRE_SCALAR` est une option de filtre et non un filtre qui indique que la variable une fois filtrée dois appartenir aux types scalaires de PHP c'est à dire `int, boolean, float, string`.
Source: 
* https://secure.php.net/manual/en/language.types.intro.php
* https://secure.php.net/manual/en/filter.filters.flags.php

Fix #136 Validation incorrecte des sorties.

---

js/ticket.js

Fix: https://github.com/mart1ver/oressource/issues/139
Explication:
Source: https://developer.mozilla.org/en/docs/Web/HTML/Element/input
Le commentaire est un DOM élément de type `<input>` il faut donc changer
sa propriété `value` et non `textContent` comme on ferait avec un `<label>`.

Fix #139 reset du commentaire dans sorties/collectes.

---

ifaces/sortiesp.php
js/ticket.js

La méthode utilisée est peu orthodoxe.
On utilise le fait que si on ne définit pas prétraitement JavaScript ignore les
arguments et ne vérifié pas si ils sont `undefined`.
C'est un hack on pourrais faire mieux.
Devrait résoudre https://github.com/mart1ver/oressource/issues/120.

Fix #120: La masse des bacs est a nouveau prise en compte.

---

INSTALL.md

En installant Oressource sur un de mes ordinateurs pour tester j'ai
constater que le manuel avait un soucis la commande SQL ne passant pas.

Correction du manuel d'installation.

---

mysql/oressource.sql

Editeur: @darnuria
Review: @darnuria
Les champs last_hero_timestamp sont mis-à-jour lors des updates
par la base de donnée. Ajour aussi de contraintes pour forcer à 0 si
certaines valeurs sont manquantes.
PR initiale: https://github.com/mart1ver/oressource/pull/187
Note d'édition: J'ai fusionné les commits et omis une correction sur le champ 'visible'.
`

Ajout de contraintes de clefs pour le schema de test

---

api/collectes.php
api/sorties.php
api/structures.php
api/ventes.php
core/session.php

Le bug se produisait si le champ saisiec etait à `non`.
Corrigé en modifiant le code pour vérifer les droits à l'aide du JSON.

Correctifs sur l'API qui empechaient la saisie d'une sortie/collecte/vente.

---

ifaces/sortiesp.php

Le numpad avait été supprimé puis mal replacé dans des commits précédents.

Fix Sorties poubelles emplacement numpad.

---

core/requetes.php
ifaces/bilanv.php

Le bug empechait d'afficher les bilans pour un point donné. Il s'agisait d'une
erreur de frappe dans l'appel des fonctions pour les requêtes SQL et d'un oubli
de champ dans la requête sql.

Résolution d'erreurs SQL et PHP dans les bilanv.

---

js/ventes.js

Quelques modifications dans `ventes.js`.
Maintenant `reset` remet à zéro le rendu monnaie et le numpad.

💊 Fix de l'absence de reset du rendu et du numpad sur les ventes.

---

mysql/2017-12-24_conformite_strict_SQL.sql

On avait des champs `text` qui pouvaient être des `INT` et d'autres des `DECIMALS`.

🚧 Changements dans le schema SQL champs passé de text à int/DECIMAL.

---

core/requetes.php
ifaces/sortiesr.php

On avait modifier le contenu du champs accepte_types_dechets.
C'était devenu une map indexé par les types de dechets pris en compte
par le recycleur et non un array.
A titre temporaire on va supporter les deux representations.

Fix d'un bug dans sortirsr.php.

---

js/ventes.js

Ça donnera par exemple « matériel électr… » par défaut on tronque à 15
caractères.

Dans les ventes sur l'interface de saisie troncature des noms.

---

js/ventes.js

Fix pour les pesées vendus: On pesse la vente en totalité, pas une masse
unitaire de chaque objet.
Le commentaire explique la méthode que nous avons retenu pour ajouter
un objet au panier.

Fix + Ajout d'un commentaire d'intention sur `add()`

---

core/requetes.php
ifaces/bilanv.php

Corrige aussi le fait qu'on comptais les points de ventes «non visibles».
On gagne ausi une requête et supprime du code.

Suppression d'une fonction/requête inutile nb_points_ventes.

---

core/requetes.php
ifaces/modification_conventions_sorties.php

La fonction était dupliquée et portait un nom différent dans
`modification_conventions_sorties.php`, la fonction sera à présent dans
`requetes.php` à coté des autres fonctions de traitement des convention.

Suppression d'une fonction dupliquée.

---

ifaces/remboursement.php

Trouvé avec @mart1ver aujourd'hui il était possible d'avoir des remboursements
avec l'id_type_dechet à 0.
Corrige: https://github.com/mart1ver/oressource/issues/347

Corrige un bug grave dans les remboursment.

---

core/requetes.php
ifaces/bilanv.php
moteur/remboursement_post.php

Les remboursements à 0 euros étaient comptés comme des ventes,
maintenant ce n'est plus possible d'avoir des remboursements à 0.
Un autre bug affectais le calcul du nombre de remboursement.

Fix d'un bug sur les remboursements

---

core/requetes.php

Suite à un échange avec les caissières c'est plus pratique et pertinent
d'avoir sur les objets, types de collectes et plus, une sortie par ordre
lexicographique (ordre alphabétique + nombres).

Reintroduction des résultats par ordre lexiconographique

---

ifaces/viz_vente.php

On demandai les droits de vérifications alors qu'il suffisait d'avoir
les capacité de ventes.

Fix d'un bug dans la visualisation des tickets de caisse.

---

core/requetes.php

L'erreur principale était celle ci:
```
[Thu Apr 18 10:48:18 2019] PHP Fatal error:  Uncaught TypeError:
Return value of login_user() must be of the type array,
boolean returned in /Oressource/oressource/core/requetes.php:452
Stack trace:
login_user(Object(PDO), 'admin@oressourc...', '1234')
thrown in /Oressource/oressource/core/requetes.php on line 452
[Thu Apr 18 10:48:18 2019] 127.0.0.1:48330 [200]: /moteur/login_post.php
- Uncaught TypeError: Return value of login_user() must be of the type
array, boolean returned in /Oressource/oressource/core/requetes.php:452
Stack trace:
login_user(Object(PDO), 'admin@oressourc...', '1234')
thrown in /Oressource/oressource/core/requetes.php on line 452
```

Fix de bugs de typages sur les login et insertion utilisateur

---

core/composants.php
ifaces/sorties.php
ifaces/sortiesc.php
ifaces/sortiesd.php
ifaces/sortiesp.php
ifaces/sortiesr.php
ifaces/tete.php

Avant dans certaines configurations il était possible d'avoir
une boucle de redirection infinie, maintenant si une page est
inaccessible on redirige vers `index.php`.
C'est pas du code glorieux une reecriture du code de gestion des gui
des sorties vraiment important.
https://github.com/mart1ver/oressource/issues/370

Fix #320 redirections infinies.

---

ifaces/verif_sorties.php

On se répétais un peu et y'avais du code mort allez hop hop.

Petit cleanup du code des verif_sorties

---

core/configs.php

La fonction `point_sortiePost()` contenait une erreur de frappe.
Edit by @darnuria: En vertue de la licence du projet "AGPLV3" de
Oressource, je me permet de retroporter ce fix réalisé par @Ouari qui
n'a pas laissé de moyen de le contacté.

Fix typo dans le code de `configs.php`.

---

css/ticket_impression.css
js/utils.js

Découpage de la PR de jean en sous PR https://github.com/mart1ver/oressource/pull/414

Ajout CSS pour impression tickets.
